import { Color, SquareKey } from "game/position";

type BoardDisplay = {
  code: SquareKey;
  color: Color;
};

export const boardDisplay: BoardDisplay[] = [
  { code: "a8", color: "white" },
  { code: "b8", color: "black" },
  { code: "c8", color: "white" },
  { code: "d8", color: "black" },
  { code: "e8", color: "white" },
  { code: "f8", color: "black" },
  { code: "g8", color: "white" },
  { code: "h8", color: "black" },
  { code: "a7", color: "black" },
  { code: "b7", color: "white" },
  { code: "c7", color: "black" },
  { code: "d7", color: "white" },
  { code: "e7", color: "black" },
  { code: "f7", color: "white" },
  { code: "g7", color: "black" },
  { code: "h7", color: "white" },
  { code: "a6", color: "white" },
  { code: "b6", color: "black" },
  { code: "c6", color: "white" },
  { code: "d6", color: "black" },
  { code: "e6", color: "white" },
  { code: "f6", color: "black" },
  { code: "g6", color: "white" },
  { code: "h6", color: "black" },
  { code: "a5", color: "black" },
  { code: "b5", color: "white" },
  { code: "c5", color: "black" },
  { code: "d5", color: "white" },
  { code: "e5", color: "black" },
  { code: "f5", color: "white" },
  { code: "g5", color: "black" },
  { code: "h5", color: "white" },
  { code: "a4", color: "white" },
  { code: "b4", color: "black" },
  { code: "c4", color: "white" },
  { code: "d4", color: "black" },
  { code: "e4", color: "white" },
  { code: "f4", color: "black" },
  { code: "g4", color: "white" },
  { code: "h4", color: "black" },
  { code: "a3", color: "black" },
  { code: "b3", color: "white" },
  { code: "c3", color: "black" },
  { code: "d3", color: "white" },
  { code: "e3", color: "black" },
  { code: "f3", color: "white" },
  { code: "g3", color: "black" },
  { code: "h3", color: "white" },
  { code: "a2", color: "white" },
  { code: "b2", color: "black" },
  { code: "c2", color: "white" },
  { code: "d2", color: "black" },
  { code: "e2", color: "white" },
  { code: "f2", color: "black" },
  { code: "g2", color: "white" },
  { code: "h2", color: "black" },
  { code: "a1", color: "black" },
  { code: "b1", color: "white" },
  { code: "c1", color: "black" },
  { code: "d1", color: "white" },
  { code: "e1", color: "black" },
  { code: "f1", color: "white" },
  { code: "g1", color: "black" },
  { code: "h1", color: "white" },
];
