import type { Position } from "./types";

export const initialPosition: Position = {
  a1: { color: "white", piece: "rook" },
  a2: { color: "white", piece: "pawn" },
  a3: null,
  a4: null,
  a5: null,
  a6: null,
  a7: { color: "black", piece: "pawn" },
  a8: { color: "black", piece: "rook" },
  b1: { color: "white", piece: "knight" },
  b2: { color: "white", piece: "pawn" },
  b3: null,
  b4: null,
  b5: null,
  b6: null,
  b7: { color: "black", piece: "pawn" },
  b8: { color: "black", piece: "knight" },
  c1: { color: "white", piece: "bishop" },
  c2: { color: "white", piece: "pawn" },
  c3: null,
  c4: null,
  c5: null,
  c6: null,
  c7: { color: "black", piece: "pawn" },
  c8: { color: "black", piece: "bishop" },
  d1: { color: "white", piece: "queen" },
  d2: { color: "white", piece: "pawn" },
  d3: null,
  d4: null,
  d5: null,
  d6: null,
  d7: { color: "black", piece: "pawn" },
  d8: { color: "black", piece: "queen" },
  e1: { color: "white", piece: "king" },
  e2: { color: "white", piece: "pawn" },
  e3: null,
  e4: null,
  e5: null,
  e6: null,
  e7: { color: "black", piece: "pawn" },
  e8: { color: "black", piece: "king" },
  f1: { color: "white", piece: "bishop" },
  f2: { color: "white", piece: "pawn" },
  f3: null,
  f4: null,
  f5: null,
  f6: null,
  f7: { color: "black", piece: "pawn" },
  f8: { color: "black", piece: "bishop" },
  g1: { color: "white", piece: "knight" },
  g2: { color: "white", piece: "pawn" },
  g3: null,
  g4: null,
  g5: null,
  g6: null,
  g7: { color: "black", piece: "pawn" },
  g8: { color: "black", piece: "knight" },
  h1: { color: "white", piece: "rook" },
  h2: { color: "white", piece: "pawn" },
  h3: null,
  h4: null,
  h5: null,
  h6: null,
  h7: { color: "black", piece: "pawn" },
  h8: { color: "black", piece: "rook" },
};

export const emptyPosition: Position = {
  a1: null,
  a2: null,
  a3: null,
  a4: null,
  a5: null,
  a6: null,
  a7: null,
  a8: null,
  b1: null,
  b2: null,
  b3: null,
  b4: null,
  b5: null,
  b6: null,
  b7: null,
  b8: null,
  c1: null,
  c2: null,
  c3: null,
  c4: null,
  c5: null,
  c6: null,
  c7: null,
  c8: null,
  d1: null,
  d2: null,
  d3: null,
  d4: null,
  d5: null,
  d6: null,
  d7: null,
  d8: null,
  e1: null,
  e2: null,
  e3: null,
  e4: null,
  e5: null,
  e6: null,
  e7: null,
  e8: null,
  f1: null,
  f2: null,
  f3: null,
  f4: null,
  f5: null,
  f6: null,
  f7: null,
  f8: null,
  g1: null,
  g2: null,
  g3: null,
  g4: null,
  g5: null,
  g6: null,
  g7: null,
  g8: null,
  h1: null,
  h2: null,
  h3: null,
  h4: null,
  h5: null,
  h6: null,
  h7: null,
  h8: null,
};
